# Generated by Django 3.2.3 on 2021-06-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['subscriber'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Укажите наименование ингридиента', max_length=150, verbose_name='Наименование')),
                ('dimension', models.CharField(help_text='Укажите единицу измерения', max_length=20, verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиент для рецепта',
                'verbose_name_plural': 'Ингредиенты для рецепта',
                'ordering': ['ingredient'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Указывается автоматически', verbose_name='Дата публикации')),
                ('title', models.CharField(help_text='Укажите наименование рецепта', max_length=250, verbose_name='Наименование')),
                ('description', models.CharField(help_text='Укажите описание рецепта', max_length=550, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Прикрепите фото рецепта', upload_to='', verbose_name='Фото')),
                ('cooking_time', models.PositiveIntegerField(help_text='Укажите время приготовления в минутах', verbose_name='Время приготовления, мин.')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=10, verbose_name='Таг')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UsersTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('tag', models.ForeignKey(help_text='Добавленный в избранное рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='userstags', to='recipes.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Пользовательский Тэг',
                'verbose_name_plural': 'Пользовательские тэги',
                'ordering': ['pk'],
            },
        ),
    ]
