# Generated by Django 3.2.3 on 2021-06-01 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_favoriterecipes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipes',
            name='user',
            field=models.ForeignKey(
                help_text='Тот кто включает в избранное',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_authors',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь'),
        ),
    ]
