# Generated by Django 3.2.3 on 2021-06-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20210601_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='customer',
            field=models.ForeignKey(help_text='Тот кто включает в список покупок', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
