# Generated by Django 3.2.3 on 2021-06-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_purchases_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name='Color'),
        ),
    ]
