# Generated by Django 3.2.3 on 2021-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Прикрепите фото рецепта',
                upload_to='',
                verbose_name='Фото'),
        ),
    ]
