# Generated by Django 3.2.3 on 2021-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(help_text='Прикрепите фото рецепта', upload_to='', verbose_name='Фото'),
        ),
    ]
