# Generated by Django 3.2.3 on 2021-06-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210622_0857'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userstags',
            name='unique_usertag',
        ),
    ]
