# Generated by Django 3.2.3 on 2021-06-22 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_userstags_unique_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstags',
            name='tag',
            field=models.ForeignKey(
                help_text='Добавленный в избранное рецепт',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='userstags',
                to='recipes.tags',
                verbose_name='Тэг'),
        ),
    ]
