# Generated by Django 3.2.3 on 2021-06-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_userstags_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={
                'ordering': ['pk'],
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='userstags',
            options={
                'ordering': ['pk'],
                'verbose_name': 'Пользовательский Тэг',
                'verbose_name_plural': 'Пользовательские тэги'},
        ),
    ]
